[tool.pyright]
reportMissingImports = "none"
reportAssignmentType = "none"
reportReturnType = "none"
reportGeneralTypeIssues = "none"
reportUndefinedVariable = "none"
reportOptionalMemberAccess = "none"
reportAttributeAccessIssue = "none"
reportPossiblyUnboundVariable = "none"